// ─── Deck Manager — File I/O for Commander decks ─────────────────────────────
// Saves and loads decks as JSON + formatted text files in the ./decks/ directory.

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve, join } from 'node:path';

// ═══════════════════════════════════════════════════════════════════════════════
// Interfaces
// ═══════════════════════════════════════════════════════════════════════════════

export interface DeckCard {
  name: string;
  quantity: number; // usually 1 for Commander (except basic lands)
  category: string;
  manaCost?: string;
  notes?: string; // why this card was included
}

export interface DeckMetadata {
  commander: string;
  theme: string;
  colors: string[]; // e.g., ["W", "U", "B", "R", "G"]
  createdAt: string;
  lastModified: string;
  totalCards: number;
}

export interface Deck {
  metadata: DeckMetadata;
  cards: DeckCard[];
}

// ═══════════════════════════════════════════════════════════════════════════════
// Helpers
// ═══════════════════════════════════════════════════════════════════════════════

const DECKS_DIR = resolve(import.meta.dirname ?? '.', 'decks');

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[',]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

async function ensureDecksDir(): Promise<void> {
  await mkdir(DECKS_DIR, { recursive: true });
}

// Category ordering for the text file
const CATEGORY_ORDER = [
  'commander',
  'creature',
  'instant',
  'sorcery',
  'artifact',
  'enchantment',
  'planeswalker',
  'land',
  'other',
];

function categoryLabel(cat: string): string {
  const labels: Record<string, string> = {
    commander: 'COMMANDER',
    creature: 'CREATURES',
    instant: 'INSTANTS',
    sorcery: 'SORCERIES',
    artifact: 'ARTIFACTS',
    enchantment: 'ENCHANTMENTS',
    planeswalker: 'PLANESWALKERS',
    land: 'LANDS',
    other: 'OTHER',
  };
  return labels[cat.toLowerCase()] ?? cat.toUpperCase();
}

// ═══════════════════════════════════════════════════════════════════════════════
// Save / Load / List
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Save a deck to disk as both JSON and formatted text.
 */
export async function saveDeck(
  deckName: string,
  cards: DeckCard[],
  metadata: DeckMetadata,
): Promise<{ jsonPath: string; txtPath: string }> {
  await ensureDecksDir();

  const slug = slugify(deckName);
  const deck: Deck = { metadata, cards };

  const jsonPath = join(DECKS_DIR, `${slug}.json`);
  const txtPath = join(DECKS_DIR, `${slug}.txt`);

  await writeFile(jsonPath, JSON.stringify(deck, null, 2), 'utf-8');
  await writeFile(txtPath, formatDeckAsText(deck), 'utf-8');

  return { jsonPath, txtPath };
}

/**
 * Load a deck from its JSON file.
 */
export async function loadDeck(deckName: string): Promise<Deck> {
  const slug = slugify(deckName);
  const jsonPath = join(DECKS_DIR, `${slug}.json`);
  const raw = await readFile(jsonPath, 'utf-8');
  return JSON.parse(raw) as Deck;
}

/**
 * List all saved decks in the decks/ directory.
 */
export async function listDecks(): Promise<string[]> {
  await ensureDecksDir();
  const files = await readdir(DECKS_DIR);
  return files
    .filter((f) => f.endsWith('.json'))
    .map((f) => f.replace(/\.json$/, ''));
}

// ═══════════════════════════════════════════════════════════════════════════════
// Formatting
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Format a deck as a human-readable text file.
 */
function formatDeckAsText(deck: Deck): string {
  const { metadata, cards } = deck;
  const lines: string[] = [
    `// MTG Commander Deck: ${metadata.commander}`,
    `// Theme: ${metadata.theme}`,
    `// Colors: ${metadata.colors.join('/')}`,
    `// Total Cards: ${metadata.totalCards}`,
    `// Generated by Squad MTG Deck Builder`,
    ``,
  ];

  // Group cards by category
  const groups = new Map<string, DeckCard[]>();
  for (const card of cards) {
    const cat = card.category.toLowerCase();
    if (!groups.has(cat)) groups.set(cat, []);
    groups.get(cat)!.push(card);
  }

  // Output in category order
  for (const cat of CATEGORY_ORDER) {
    const catCards = groups.get(cat);
    if (!catCards || catCards.length === 0) continue;

    const count = catCards.reduce((sum, c) => sum + c.quantity, 0);
    const label = categoryLabel(cat);

    lines.push(`=== ${label} (${count}) ===`);
    for (const card of catCards) {
      lines.push(`${card.quantity}x ${card.name}`);
    }
    lines.push('');
  }

  // Any categories not in the standard order
  for (const [cat, catCards] of groups) {
    if (CATEGORY_ORDER.includes(cat)) continue;
    const count = catCards.reduce((sum, c) => sum + c.quantity, 0);
    lines.push(`=== ${cat.toUpperCase()} (${count}) ===`);
    for (const card of catCards) {
      lines.push(`${card.quantity}x ${card.name}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Format a deck as text for the squad to analyze (prompt context).
 */
export function formatDeckForPrompt(deck: Deck): string {
  const { metadata, cards } = deck;
  const lines: string[] = [
    `Current deck: "${metadata.commander}" (${metadata.theme})`,
    `Colors: ${metadata.colors.join('/')}`,
    `Total cards: ${metadata.totalCards}`,
    ``,
  ];

  const groups = new Map<string, DeckCard[]>();
  for (const card of cards) {
    const cat = card.category.toLowerCase();
    if (!groups.has(cat)) groups.set(cat, []);
    groups.get(cat)!.push(card);
  }

  for (const cat of CATEGORY_ORDER) {
    const catCards = groups.get(cat);
    if (!catCards || catCards.length === 0) continue;
    lines.push(`**${categoryLabel(cat)}:**`);
    for (const card of catCards) {
      const notes = card.notes ? ` — ${card.notes}` : '';
      const mana = card.manaCost ? ` (${card.manaCost})` : '';
      lines.push(`  ${card.quantity}x ${card.name}${mana}${notes}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Parse a deck from the squad's text response.
 *
 * Looks for lines like "1x Card Name" or "1 Card Name" and tries to infer
 * categories from section headers. Falls back to the existing deck's
 * categories if provided.
 */
export function parseDeckFromResponse(
  response: string,
  existingDeck?: DeckCard[],
): { cards: DeckCard[]; commander: string; theme: string; colors: string[] } {
  const existingMap = new Map<string, DeckCard>();
  if (existingDeck) {
    for (const card of existingDeck) {
      existingMap.set(card.name.toLowerCase(), card);
    }
  }

  const cards: DeckCard[] = [];
  const seenNames = new Set<string>();
  let currentCategory = 'other';
  let commander = '';
  let theme = '';
  let colors: string[] = [];

  const categoryPatterns: Record<string, RegExp> = {
    commander: /commander/i,
    creature: /creature/i,
    instant: /instant/i,
    sorcery: /sorcer/i,
    artifact: /artifact/i,
    enchantment: /enchantment/i,
    planeswalker: /planeswalker/i,
    land: /land/i,
  };

  // Try to extract metadata from response
  const themeMatch = response.match(/theme[:\s]+["']?([^"'\n]+)/i);
  if (themeMatch) theme = themeMatch[1]!.trim();

  const colorMatch = response.match(/colors?[:\s]+([WUBRGC][/,\s]*(?:[WUBRGC][/,\s]*)*)/i);
  if (colorMatch) {
    colors = colorMatch[1]!
      .split(/[/,\s]+/)
      .map((c) => c.trim().toUpperCase())
      .filter((c) => /^[WUBRGC]$/.test(c));
  }

  const lines = response.split('\n');

  for (const line of lines) {
    const trimmed = line.trim();

    // Detect section headers (e.g., "=== CREATURES ===" or "## Creatures" or "**Creatures:**")
    const headerMatch = trimmed.match(
      /^(?:={2,}|#{1,4}|\*{2,})\s*(.+?)(?:\s*\(\d+\))?\s*(?:={2,}|#{0,4}|\*{0,2}:?)$/
    );
    if (headerMatch) {
      const headerText = headerMatch[1]!;
      for (const [cat, pattern] of Object.entries(categoryPatterns)) {
        if (pattern.test(headerText)) {
          currentCategory = cat;
          break;
        }
      }
      continue;
    }

    // Also detect simpler headers like "Creatures:" or "**Creatures (30):**"
    const simpleHeader = trimmed.match(/^\*{0,2}([A-Za-z]+)(?:\s*\(\d+\))?\*{0,2}:?\s*$/);
    if (simpleHeader) {
      const headerText = simpleHeader[1]!;
      for (const [cat, pattern] of Object.entries(categoryPatterns)) {
        if (pattern.test(headerText)) {
          currentCategory = cat;
          break;
        }
      }
    }

    // Parse card lines: "1x Card Name", "1 x Card Name", "1 Card Name", "- 1x Card Name"
    const cardMatch = trimmed.match(
      /^[-*•]?\s*(\d+)\s*x?\s+(.+?)(?:\s*[-—]\s*.+)?$/
    );
    if (cardMatch) {
      const quantity = parseInt(cardMatch[1]!, 10);
      let name = cardMatch[2]!.trim();

      // Strip trailing notes in parentheses or after dashes
      name = name.replace(/\s*\(.*?\)\s*$/, '').trim();
      // Strip markdown formatting
      name = name.replace(/\*+/g, '').replace(/`/g, '').trim();

      if (!name || name.length < 2 || seenNames.has(name.toLowerCase())) continue;
      seenNames.add(name.toLowerCase());

      // Pull existing card data if available
      const existing = existingMap.get(name.toLowerCase());

      const card: DeckCard = {
        name,
        quantity,
        category: currentCategory,
        manaCost: existing?.manaCost,
        notes: existing?.notes,
      };

      if (currentCategory === 'commander' && !commander) {
        commander = name;
      }

      cards.push(card);
    }
  }

  // If no commander found in sections, use the first card
  if (!commander && cards.length > 0) {
    commander = cards[0]!.name;
    cards[0]!.category = 'commander';
  }

  return { cards, commander, theme, colors };
}
